# Generated by Django 6.0 on 2026-03-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(help_text="From 'Marca temporal'")),
                ('first_name', models.CharField(help_text="From 'Nombre'", max_length=100)),
                ('last_name', models.CharField(help_text="From 'Apellido'", max_length=100)),
                ('dni', models.CharField(help_text="From 'Cédula de Identidad '", max_length=20, unique=True)),
                ('phone', models.CharField(help_text="From 'Número de Teléfono Principal'", max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, help_text="From 'Nombre Completo del Contacto de Emergencia'", max_length=150, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text="From 'Número de Teléfono del Contacto de Emergencia '", max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text="From 'Dirección de Residencia Completa'", null=True)),
                ('has_medical_condition', models.BooleanField(default=False, help_text="True if '¿Tiene alguna lesión...?' is 'Sí'")),
                ('medical_details', models.TextField(blank=True, help_text="From 'Si respondió 'Sí'...'", null=True)),
                ('search_name_vector', models.CharField(db_index=True, editable=False, help_text='Normalized full name for OCR matching', max_length=255)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
