# Generated by Django 6.0 on 2026-03-25 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('entry_method', models.CharField(choices=[('MANUAL', 'Ingreso Manual (Sistema)'), ('WHATSAPP', 'Captura de WhatsApp (OCR)'), ('QR', 'Código QR / Lector')], default='MANUAL', max_length=15)),
                ('ocr_raw_text', models.CharField(blank=True, help_text='Texto original extraído de la imagen si se usó OCR.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-timestamp'],
            },
        ),
    ]
