# Generated by Django 6.0 on 2026-04-02 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Crossfit, Funcional, Yoga', max_length=100)),
                ('schedule_time', models.TimeField(help_text='Horario de la clase')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_debt',
            field=models.BooleanField(default=False, help_text='True si el cliente asistió sin tener clases disponibles (Moroso)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='Entrenador que impartió la clase', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ocr_raw_text',
            field=models.CharField(blank=True, help_text='Texto extraído del OCR.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(help_text='Cliente que asiste.', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='training_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.trainingclass'),
        ),
    ]
