# Generated by Django 6.0 on 2026-04-05 23:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: USD, VES', max_length=3, unique=True)),
                ('symbol', models.CharField(help_text='Ej: $, Bs.', max_length=5)),
                ('is_base', models.BooleanField(default=False, help_text='True solo para USD')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPlan', models.CharField(help_text='Ej: MENS-12', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('class_limit', models.IntegerField(default=1, help_text='Total de clases incluidas')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Abono Parcial'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=15)),
                ('emission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exchange_rate_emission', models.DecimalField(decimal_places=4, help_text='Tasa al momento de crear factura', max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('POS', 'Punto de Venta'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Monto transferido o entregado', max_digits=15)),
                ('exchange_rate_payment', models.DecimalField(decimal_places=4, help_text='Tasa BCV del momento del pago', max_digits=15)),
                ('equivalent_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payments/receipts/')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.currency')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=15)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payments.currency')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'unique_together': {('currency', 'effective_date')},
            },
        ),
    ]
