# Generated by Django 6.0 on 2026-04-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='end_date',
            field=models.DateField(blank=True, help_text='Calculado automáticamente según el plan', null=True),
        ),
    ]
