# Generated by Django 6.0 on 2026-04-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('POS', 'Punto de Venta'), ('TRANSFER', 'Transferencia'), ('CHANGE', 'Vuelto / Cambio')], default='CASH', max_length=20),
        ),
    ]
