# Generated by Django 6.0 on 2026-03-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_injuries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='injury_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Lesiones, alergias o condiciones médicas reportadas en la ficha.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(help_text='Cédula o RIF sin letras.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('J', 'Jurídico'), ('P', 'Pasaporte')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='internal_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Personal / Entrenador'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
