# Generated by Django 6.0 on 2026-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_name',
            field=models.CharField(db_index=True, default='', editable=False, help_text='Nombre normalizado para búsquedas OCR', max_length=255),
        ),
    ]
