# Generated by Django 6.0 on 2026-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_birth_date_remove_user_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_attendance_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
