# Generated by Django 6.0 on 2026-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('EXPIRED', 'Vencido'), ('DEBTOR', 'Moroso')], default='EXPIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='remaining_classes',
            field=models.IntegerField(default=0),
        ),
    ]
